- name: Create database
  mysql_db:
    login_user: root
    login_password: '{{ guacamole_mysql_root_password }}'
    name: '{{ guacamole_db_name }}'
    encoding: utf8
    state: present
  register: db_created

- name: Create database user
  mysql_user:
    login_user: root
    login_password: '{{ guacamole_mysql_root_password }}'
    name: '{{ guacamole_db_username }}'
    password: '{{ guacamole_db_password }}'
    priv: '{{ guacamole_db_name }}.*:SELECT,INSERT,UPDATE,DELETE'
  when: db_created|changed

- name: Create database schema
  mysql_db:
    login_user: root
    login_password: '{{ guacamole_mysql_root_password }}'
    name: '{{ guacamole_db_name }}'
    state: import
    target: '{{ guacamole_temp_path }}/guacamole-auth-jdbc-0.9.11-incubating/mysql/schema/001-create-schema.sql'
  when: db_created|changed

- name: Create guacamole admin user
  mysql_db:
    login_user: root
    login_password: '{{ guacamole_mysql_root_password }}'
    name: '{{ guacamole_db_name }}'
    state: import
    target: '{{ guacamole_temp_path }}/guacamole-auth-jdbc-0.9.11-incubating/mysql/schema/002-create-admin-user.sql'
  when: db_created|changed
